#ifndef SSPAPPLICATION_COMPONENT_COMPONENTSTRUCTS
#define SSPAPPLICATION_COMPONENT_COMPONENTSTRUCTS
#include <DirectXMath.h>
#include <vector>

enum EVENT
{
	COLLIDED,
	BUTTON_PRESSED,
	BUTTON_TOGGLED,
	DOOR_OPENED,
	DOOR_CLOSED
};

#endif