#ifndef SSPAPPLICATION_COMPONENT_COMPONENTSTRUCTS
#define SSPAPPLICATION_COMPONENT_COMPONENTSTRUCTS
#include <DirectXMath.h>
#include <vector>

enum EVENT
{
	COLLIDED,
	BUTTON_DEACTIVE,
	BUTTON_ACTIVE,
	LEVER_DEACTIVE,
	LEVER_ACTIVE,
	DOOR_OPENED,
	DOOR_CLOSED,
	WHEEL_INCREASING,
	WHEEL_DECREASING,
	WHEEL_0,
	WHEEL_10,
	WHEEL_20,
	WHEEL_30,
	WHEEL_40,
	WHEEL_50,
	WHEEL_60,
	WHEEL_70,
	WHEEL_80,
	WHEEL_90,
	WHEEL_100
};

#endif