#ifndef GRAPHICSDLL_ANIMATIONS_ANIMATIONSTATEENUMS_H
#define GRAPHICSDLL_ANIMATIONS_ANIMATIONSTATEENUMS_H

#ifdef GRAPHICSDLL_EXPORTS
#define GRAPHICSDLL_API __declspec(dllexport)
#else
#define GRAPHICSDLL_API __declspec(dllimport)
#endif

enum AnimationStates : int
{
	PLAYER_IDLE = 0, 
	PLAYER_RUN_FORWARD,
	PLAYER_RUN_BACKWARD,
	PLAYER_RUN_RIGHT,
	PLAYER_RUN_LEFT,
	PLAYER_PICKUP,
	PLAYER_BALL_IDLE,
	PLAYER_THROW,
	PLAYER_RUN_FORWARD_BALL,
	PLAYER_RUN_BACKWARD_BALL,
	PLAYER_RUN_LEFT_BALL,
	PLAYER_RUN_RIGHT_BALL,
	RAGDOLL_STATE,
	ANIMATION_ERROR
};

enum Blending
{
	NO_TRANSITION = 0,
	SMOOTH_TRANSITION = 1,
	FROZEN_TRANSITION =	2
};

enum FootSoundSynch
{
	PLAYER_STUDLEY, 
	PLAYER_ABBINGTON, 
	RIGHT_FOOT = 15,
	LEFT_FOOT = 19
};

#endif